# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_pb2 as hello__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/hello.Greeter/SayHello',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def SayHello(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hello.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DiffSubscriberStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Subscribe = channel.unary_unary(
        '/hello.DiffSubscriber/Subscribe',
        request_serializer=hello__pb2.DiffSubscribe.SerializeToString,
        response_deserializer=hello__pb2.DiffNotification.FromString,
        )
    self.SubscribeStream = channel.unary_stream(
        '/hello.DiffSubscriber/SubscribeStream',
        request_serializer=hello__pb2.DiffSubscribe.SerializeToString,
        response_deserializer=hello__pb2.DiffNotification.FromString,
        )


class DiffSubscriberServicer(object):
  """The greeting service definition.
  """

  def Subscribe(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeStream(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiffSubscriberServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Subscribe': grpc.unary_unary_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=hello__pb2.DiffSubscribe.FromString,
          response_serializer=hello__pb2.DiffNotification.SerializeToString,
      ),
      'SubscribeStream': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeStream,
          request_deserializer=hello__pb2.DiffSubscribe.FromString,
          response_serializer=hello__pb2.DiffNotification.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hello.DiffSubscriber', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
